[lib]
proc-macro = true

[package]
name = "mzsh-commandenum_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version="2.0.39", features=["full","fold"]}
quote = "1.0.33"
proc-macro2 = "1.0.69"
